<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Implementation of hook_menu().
 */
function wap_menu() {
  $items = array();
  $items['calc'] = array(
      'title'           => 'Calculator',
      'description'     => 'Calculator',
      'page callback'   => 'wap_calc',
      'access callback' => TRUE,
      'type'            => MENU_CALLBACK,
  );
  $items['jasmine'] = array(
    'title'           => 'Jasmine Spec Runner',
    'description'     => 'Run Jasmine tests for the site.',
    'page callback'   => 'wap_jasmine',
    'access callback' => TRUE,
    'type'            => MENU_CALLBACK,
    'file'            => 'wap.jasmine.inc',
  );
  $items['jasminexml'] = array(
    'title'           => 'Jasmine Spec Runner',
    'description'     => 'Run Jasmine tests for the site.',
    'page callback'   => 'wap_jasmine_xml',
    'access callback' => TRUE,
    'type'            => MENU_CALLBACK,
    'file'            => 'wap.jasmine.inc',
  );
  return $items;
}


/**
 * Implementation of hook_theme().
 */
function wap_theme() {
  $themes['wap_calc'] = array(
      'template'  => 'wap_calc',
      'variables' => array()
  );
  $themes['jasmine_specrunner'] = array(
    'template'  => 'wap.specrunner',
    'variables' => array()
  );
  $themes['jasmine_specrunner_xml'] = array(
    'template'  => 'templates/wap.specrunner.xml',
    'variables' => array()
  );
  
  // Theme overrides --------------
  $themes['page__jasmine'] = array(
    'template'  => 'templates/wap.page__jasmine',
    'variables' => array()
  );
  $themes['html__jasmine'] = array(
    'template'  => 'templates/wap.html__jasmine',
    'variables' => array()
  );
  $themes['page__jasminexml'] = array(
    'template'  => 'templates/wap.page__jasminexml',
    'variables' => array()
  );
  $themes['html__jasminexml'] = array(
    'template'  => 'templates/wap.html__jasminexml',
    'variables' => array()
  );
  return $themes;
}

function wap_calc() {
  return theme('wap_calc');
}
